# Generated by Django 3.2.5 on 2021-07-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
