# Generated by Django 3.2.5 on 2021-07-10 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20210708_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
